contracts/BorrowerOperations.sol, contracts/Dependencies/GravitaBase.sol, contracts/Interfaces/IBorrowerOperations.sol, contracts/StabilityPool.sol, test/gravita/AccessControlTest.js
Closes #123 
Closes #132 
Closes #77
=> Remove unused functions.

contracts/BorrowerOperations.sol, contracts/VesselManager.sol
=> Remove unnecessary code

contracts/ActivePool.sol, contracts/FeeCollector.sol, contracts/StabilityPool.sol, contracts/VesselManager.sol, contracts/VesselManagerOperations.sol
Closes #106 #104  #97 #76 #124 #73
=> Remove redundant isInitialized.

contracts/Timelock.sol
=> Remove getBlockTimestamp().

contracts/FeeCollector.sol, contracts/GRVT/CommunityIssuance.sol, contracts/GRVT/GRVTStaking.sol, contracts/Interfaces/IFeeCollector.sol, test/gravita/FeeCollectorTest.js, utils/testHelpers.js
=> fix: [FCR-01S] Data Location Optimizations

contracts/DebtToken.sol, contracts/StabilityPool.sol
=> Gas optimizations.

contracts/Timelock.sol
=> fix: [TKC-01C] Inefficient Application of Access Control

contracts/VesselManagerOperations.sol
=> Optimizing for loops.

contracts/SortedVessels.sol
=> Remove isInitialized.

contracts/Dependencies/GravitaMath.sol
=> [79] Add constant.

contracts/Dependencies/ERC20Permit.sol
=> fix: [ERC-04C] Variable Mutability Specifier (Immutable)

contracts/Dependencies/GravitaMath.sol
=> fix: GMH-01C: Illegible Representation of Value Literal

contracts/DebtToken.sol, contracts/Interfaces/IDebtToken.sol
=> fix: [A21] - I-naming inconsistent

contracts/StabilityPool.sol, contracts/VesselManager.sol
=> fix: [SPL-02C] and [VMR-01C] Inefficient mapping Lookups

contracts/AdminContract.sol, contracts/BorrowerOperations.sol, contracts/Interfaces/IAdminContract.sol, test/gravita/BorrowerOperationsTest.js
=> fix: [A15] - No explicit check in BorrowerOperations::openVessel that the collateral deposited by the user is approved

contracts/FeeCollector.sol
=> fix: [FCR-01C] Inefficient mapping Lookups

contracts/Dependencies/ERC20Permit.sol
=> fix: [ERC-01C] Inefficient mapping Lookups

contracts/BorrowerOperations.sol
=> fix: [BOS-03C] Suboptimal Struct Declaration

contracts/AdminContract.sol, contracts/Interfaces/IAdminContract.sol, contracts/VesselManagerOperations.sol, test/gravita/VesselManagerTest.js
fixes #54 and #55 and #56 and #57 and #30
=> fix: [ACT-01C] [ACT-02C] [ACT-03C] [ACT-04C] [ACT-01S]

contracts/Dependencies/SafetyTransfer.sol, contracts/Interfaces/IERC20Decimals.sol
=> fix: [ERD-01C] Non-Standard Interface Name

contracts/CollSurplusPool.sol
=> fix: [CSP-02C] Inefficient mapping Lookups

contracts/SortedVessels.sol
=> fix: [SVS-02C] Inefficient mapping Lookups

contracts/Dependencies/SafetyTransfer.sol, contracts/TestContracts/ERC20DecimalsMock.sol, contracts/TestContracts/SafetyTransferTester.sol, test/gravita/SafetyTransferTest.js
=> fix: [STR-02M] Insecure Conversion of Amount & [STR-01M] Incorrect Decimal Assumption

contracts/FeeCollector.sol
=> Fix loop increment.

contracts/Interfaces/ISortedVessels.sol, contracts/SortedVessels.sol
=> Remove isFull, maxSize.

contracts/Timelock.sol
=> Revert if eta longer that delay + GRACE_PERIOD.

contracts/Interfaces/IVesselManagerOperations.sol, contracts/VesselManagerOperations.sol, test/gravita/VesselManagerTest.js
=> Enforce a batch size limit.

contracts/StabilityPool.sol, contracts/TestContracts/StabilityPoolTester.sol
=> Moving _leftSumColls code to tester contract.

contracts/Interfaces/IVesselManagerOperations.sol, contracts/VesselManagerOperations.sol
=> Remove unused code.

contracts/BorrowerOperations.sol
=> Remove unused modifiers.

contracts/VesselManager.sol
=> Remove redundant check.

contracts/Timelock.sol
=> Adding receive function to be future proof.

contracts/StabilityPool.sol, contracts/VesselManager.sol
=> Add missing ownable_init.

contracts/Dependencies/ERC20Permit.sol, contracts/TestContracts/DebtTokenTester.sol, test/gravita/DebtTokenTest.js, test/gravita/GrowthTokenTest.js
=> Update chainId if it ever changes.

contracts/AdminContract.sol, contracts/BorrowerOperations.sol, contracts/CollSurplusPool.sol, contracts/DebtToken.sol, contracts/Dependencies/ERC20Permit.sol, contracts/Dependencies/GravitaMath.sol, contracts/FeeCollector.sol, contracts/Interfaces/IVesselManagerOperations.sol, contracts/PriceFeed.sol, contracts/SortedVessels.sol, contracts/StabilityPool.sol, contracts/TestContracts/StabilityPoolTester.sol, contracts/Timelock.sol, contracts/VesselManager.sol, contracts/VesselManagerOperations.sol, test/liquity/StabilityPool_SPWithdrawalTest.js
=> Gas improve

contracts/Addresses.sol, contracts/BorrowerOperations.sol
Fix issue when we transfer tokens for gas comp even when they're 0.
=> Fix zero transfer

contracts/Interfaces/IVesselManagerOperations.sol, contracts/VesselManagerOperations.sol, test/gravita/CollSurplusPoolTest.js, test/gravita/VesselManagerTest.js, test/gravita/VesselManager_RecoveryModeTest.js
Convert the constant redemption softening param into a variable.
=> Variable redemption soften param

contracts/Interfaces/IPriceFeed.sol, contracts/PriceFeed.sol, contracts/Pricing/PriceFeedL2.sol, contracts/TestContracts/MockAggregator.sol, test/gravita/PriceFeedTest.js
=> Pricefeed L2

contracts/DebtToken.sol, contracts/Dependencies/AddressesConfigurable.sol, contracts/Interfaces/IVesselManagerOperations.sol, contracts/VesselManagerOperations.sol, test/gravita/PriceFeedTest.js
=> Sanitize addresses. Add missing event.

contracts/Interfaces/IPriceFeed.sol, contracts/PriceFeed.sol, contracts/VesselManagerOperations.sol, test/gravita/PriceFeedTest.js
=> Issue 382 constant

contracts/PriceFeed.sol
=> Add gas optimization

README.md
Hello,
Corrected the subject-verb agreement in the sentence.
- Changed "logic and data is" to "logic and data are" for proper subject-verb agreement.
The original sentence contained a compound subject ("logic and data"), and the verb "are" is more appropriate for agreement with compound subjects.
Thank you.
=> Fix Subject-Verb Agreement in Sentence
